package com.bcarranza.conoceu

class PlaceProvider {
    companion object{
        val schoolList = listOf<Place>(
            Place(
                R.string.fic_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.fime_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.farq_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.facdyc_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.ffyl_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.facpya_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.ftsydh_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.fod_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.fcb_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.fcq_school,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.fcfm_school,
                R.drawable.small_logoconoceu_03
            )
        )

        val placeList = listOf<Place>(
            Place(
                R.string.medicalserivces_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.ctycd_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.bookstore_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.library_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.schoolarship_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.dti_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.deya_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.rectoria_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.cedye_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.ci_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.libraryuniversity_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.cae_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.drh_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.caou_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.dgp_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.dgdsayn_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.gasparmass_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.chicorivera_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.park_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.print_place,
                R.drawable.small_logoconoceu_03
            ),
            Place(
                R.string.stadium_place,
                R.drawable.small_logoconoceu_03
            )
        )
    }
}